[project]
name = "mytest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
